# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
	pod 'RxSwift'
end

target 'MVVMExample' do
	use_frameworks!
	shared_pods
end

