# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RxDataSources'
end

target 'ReactiveExample' do
	use_frameworks!
	shared_pods
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		if target.name == 'RxSwift'
			target.build_configurations.each do |config|
				if config.name == 'Debug'
					config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
				end
			end
		end
	end
end

