# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
	pod 'RxSwift'
	pod 'RxDataSources'
end

target 'ReactiveExample' do
	use_frameworks!
	shared_pods
end

